repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
      - id: check-ast
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: check-json
      - id: check-toml
      - id: debug-statements
      - id: detect-private-key
      - id: double-quote-string-fixer
      - id: mixed-line-ending
      # - id: pretty-format-json
      - id: name-tests-test
        args: [--pytest-test-first]
