name: Release

on:
  push:
    tags:
      - 'v*.*.*'

permissions:
  contents: write

jobs:
  build-and-test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            artifact_name: synthgen-linux
            pyinstaller_out: dist/synthgen-linux
            pyinstaller_add_data: "legal/EULA_v1.0.txt:."
          - os: windows-latest
            artifact_name: synthgen-win.exe
            pyinstaller_out: dist/synthgen-win.exe
            pyinstaller_add_data: "legal/EULA_v1.0.txt;."
          - os: macos-latest
            artifact_name: synthgen-macos
            pyinstaller_out: dist/synthgen-macos
            pyinstaller_add_data: "legal/EULA_v1.0.txt:."

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-dev.txt

      - name: Install package in editable mode
        run: pip install -e .

      - name: Run Pytest
        run: pytest -v -s tests

      - name: Build binary with PyInstaller
        run: |
          PYTHONPATH=. python -m PyInstaller synth/cli.py \
            --onefile \
            --name ${{ matrix.artifact_name }} \
            --add-data "${{ matrix.pyinstaller_add_data }}"
        shell: bash

      - name: Rename output for consistency
        run: |
          out_basename="$(basename "${{ matrix.pyinstaller_out }}")"
          if [[ "${{ matrix.artifact_name }}" != "$out_basename" ]]; then
            mv "dist/${{ matrix.artifact_name }}" "${{ matrix.pyinstaller_out }}"
          fi
        shell: bash

      - name: Create checksum
        run: |
          if [[ "${{ runner.os }}" == "Windows" ]]; then
            certutil -hashfile "${{ matrix.pyinstaller_out }}" SHA256 > "${{ matrix.pyinstaller_out }}.sha256"
          elif [[ "${{ runner.os }}" == "macOS" ]]; then
            shasum -a 256 "${{ matrix.pyinstaller_out }}" > "${{ matrix.pyinstaller_out }}.sha256"
          else
            sha256sum "${{ matrix.pyinstaller_out }}" > "${{ matrix.pyinstaller_out }}.sha256"
          fi
        shell: bash

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.artifact_name }}
          path: |
            ${{ matrix.pyinstaller_out }}
            ${{ matrix.pyinstaller_out }}.sha256
            legal/EULA_v1.0.txt

  release:
    needs: build-and-test
    runs-on: ubuntu-latest
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: dist

      - name: List downloaded files
        run: ls -R dist

      - name: Publish Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref }}
          files: |
             dist/synthgen-linux
             dist/synthgen-linux.sha256
             dist/synthgen-win.exe
             dist/synthgen-win.exe.sha256
             dist/synthgen-macos
             dist/synthgen-macos.sha256
             dist/EULA_v1.0.txt
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
